default: &default
  adapter: postgresql
  hostname: localhost
  port: 5445
  username: forest
  password: secret
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  database: forest_movies
  encoding: unicode
  pool: 5
  host: localhost
  port: 5445
  username: forest
  password: secret
